### ISSUE TITLE
Questions for ReverseClip

### ISSUE THREAD

**Issue by sambudda** [mikaelhellqvist/ReverseClip#3]
Hi Mike,

I have been testing ReverseClip and ran into a few issues. Perhaps you can help me explain a few questions I had.

Q1: Is there a delegate method that tells the program when its done processing reverse clip? So lets say I let a user select a movie from their album and then they hit the reverse button. How can I tell when the movie is done processing? i.e. when 100% reverse is compelete?

Q2: Similar to Q1, how can I get to percentage complete to my custom view controller like v1ViewController? I was thinking of showing user a percent complete dial so they know how much of movie is complete but I am not sure how can I get to percent complete as that is in RCImageSequencer.m

Q3: In the sample code the length of movie is hard coded to 2 secs. Is there a way I can get what is the length of a movie that user selected is and then pass that in outSeconds?

[compositionTool addToCompositionWithAsset:(AVURLAsset*)_asset timeRangeSpeed:kTimeRangeSlowMotion inSeconds:0.0 outSeconds:2.0 isForImageSequence:YES speed:kTimeRangeSlowMotion]; 

Q4: I recorded a 5sec landscape movie on my iphone. When I ran it through the reverse code it made the movie upside. So the ball that was falling down, in the reverse movie fell up. Any ideas how can I fix that?

Q5: Similarly a portrait video doesn't look correct when run through reverse. As you had mentioned in your stackoverflow post I need to change these variable #define FRAME_WIDTH 640
# define FRAME_HEIGHT 360

and pass the actual video width and height, correct?

Q5: This one really stumped me. I have a 5 sec video of a ball falling. I wanted to reverse it and slow it down. So what I did was in RCComposer.m I changed this line to

scaleOutTime = CMTimeMakeWithSeconds(outSeconds*10, 600); //instead of *2

and changed this to 10 secs for output

[compositionTool addToCompositionWithAsset:(AVURLAsset*)_asset timeRangeSpeed:kTimeRangeSlowMotion inSeconds:0.0 outSeconds:10.0 isForImageSequence:YES speed:kTimeRangeSlowMotion]; 

I was hoping the code will make a reverse movie that is 10 seconds long. Not the case it actually had 5 secs of black dead space and then last 5 secs of normal reverse movie speed. 

Is there a way I can make a 5 sec video slowmo and reversed. Do I need to somehow slowmo it using some other code and then run that slowmo through reverse clip?

Sorry I have asked so many questions but your sample project is great and I hope I could use it for an app. Thanks man.

**Comment by mikaelhellqvist** [comment]
hey Sam,

I will have to have a look at this issues hopefully tomorrow. I just got
the flu... wintertime...

There are solutions to your questions, but I'm too tired to have a look at
it now. Just wanted you to know that I'm still on it.

/M

**Comment by sambudda** [comment]
Take you time Mike. There is no rush. Hope you feel better

**Comment by sambudda** [comment]
never mind, I got his all working

**Comment by mikaelhellqvist** [comment]
Great to hear Sam! I'm still going to update the code, but feel free to do a pull request if you like :)

**Comment by Sergozh** [comment]
@sambudda Hi. Can u help me? When I try to reverse my movie, it quality become lower than original's movie.
